### ISSUE TITLE
Gsitemap for multistore not working with CRON

### ISSUE THREAD

**Issue by 01park** [PrestaShop/gsitemap#113]
PS 1.7.5.2 and have Gsitemap 4.1.0

When I create a cron job for shop_id=1 the created sitemap is a succes.
When I create a cron job for shop_id=2 the sitemap for shop_id=1 gets updated and nothing for  shop_id=2

When I go into shop 1 and press generate sitemap in the module, it works. If I do this for shop 2 it works to.

When I click on the link given at the bottom, a new tab opens, the page is blanc and its like something is running in the background. I remember this used to work similar in 1.6 and once this process was finished the sitemap was generated.

**Comment by khouloudbelguith** [comment]
Hi @01park,

For different shops selected you have a link cron to generate a sitemap.

- Shop 1: http://Your_shop/modules/gsitemap/gsitemap-cron.php?token=19496193e4&id_shop=1
- Shop2: http://Your_shop/modules/gsitemap/gsitemap-cron.php?token=19496193e4&id_shop=2

When you click on those links, generating a sitemap is done on the background.

THanks!

**Comment by 01park** [comment]
Hi

Yes, tried this does not work to

**Comment by khouloudbelguith** [comment]
@01park, thanks for your feedback.
I manage to reproduce the issue with v4.1.0.
When we click on this link: Shop 1: `http://Your_shop/modules/gsitemap/gsitemap-cron.php?token=19496193e4&id_shop=1`
the sitemap for the first shop is updated
we can check that in this file **lastmod**: `http://Your_shop/1_index_sitemap.xml`
When we click on this link: Shop2: `http://Your_shop/modules/gsitemap/gsitemap-cron.php?token=19496193e4&id_shop=2`
the sitemap for the first shop is updated, but the sitemap for the second shop => no.
we can check that in this file **lastmod**: `http://Your_shop/2_index_sitemap.xml`

Thanks!

**Comment by 01park** [comment]
Im happy you have confirmed it's a bug. Someone told me its my server

**Comment by mathieuhen** [comment]
Yes, i had the same bug. 
The mistake in the code is at the line 52 in gsitemap-cron.php.

The function Tools::getIsset is filled with the parameter Tools::getValue('id_shop') so it returns always FALSE. 

Replace the line 52 with this : 
`$id_shop = (Tools::getIsset('id_shop') && in_array(Tools::getValue('id_shop'), $list_id_shop)) ? (int) Tools::getValue('id_shop') : (int) Configuration::get('PS_SHOP_DEFAULT');`

**Comment by khouloudbelguith** [comment]
Hi @mathieuhen,

Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/gsitemap
Thank you!

**Comment by 01park** [comment]
Thank you for fixing this Mathieuhen,

This worked for me!

**Comment by MathiasReker** [comment]
Fixed: https://github.com/PrestaShop/gsitemap/pull/118

**Comment by 01park** [comment]
Maybe this fix could be integrated in to newer PS releases. In 1.7.6 this bug is still remaining.
