### ISSUE TITLE
could not be installed in prestashop 1.7

### ISSUE THREAD

**Issue by tom75** [PrestaShop/gsitemap#45]
Hello Prestashop-Colleagues, 

great to see that there is a sitemap module availabe, but, I just tried to use this module with prestashop 1.7.2.2 and it is not possible to install, because of 

"incorrect zip format of module" (translated freely from german).

Should this work already for prestashop 1.7.2.2 - or is it not working?

and if this one is not working, any ideas where i can find a working sitemap module for prestashop 1.7 (multishop)?

thanks in advance
tom

**Comment by AndreaLombardo** [comment]
I think you need to buy some other module... I have the same problem, but everything is for sale on prestashop marketplace...

**Comment by Mreker** [comment]
Thank you for your report! This issue is fixed here: https://github.com/PrestaShop/gsitemap/pull/53

**Comment by holographix** [comment]
Sorry to reopen this issue, but I followed all the #53 and I also downloaded a fresh version of this module but I still get the same error as the OP on PS 1.7.2.4.
Since I have plenty of sandboxes I also tried it on a fresh install, but that didn't change the outcome.
Unfortunately there's no log in the error log file.

FWIW if you unzip the folder in the modules directory it obviously works.
Thx in advance,
Aaron.
